server:
  port: 9091
spring:
  application:
    name: school
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:/www/ecampus/static/
      ,file:///E:/anzhuangruanjian/git/zj-websocket/zj-websocket-chat/files/
    
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zj_websocket?characterEncoding=utf-8
    username: root
    password: root
#  jackson:
#    serialization:
#      indent-output: true

##show sql
#logging:
#  level:
#    com:
#      zj:
#        modules:
#          mapper: debug

#  Hibernate 格式化sql
#  jpa:
#    properties:
#      hibernate:
#        format_sql: true
#        show_sql: true

mybatis:
  config-location: classpath:mybatis-config.xml
  type-aliases-package: com.zj.modules.domain
  type-handlers-package: com.zj.modules.mapper
  mapper-locations: classpath:com.zj.modules.mapper/*.xml
    
    
    